<h1><?php echo $this->title ?></h1>

<?php

$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.'/formulario/formulario/receive',
    'method' => 'post',
    'class'  => 'form-horizontal'
));

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);

?>

<div class="form_element">
    Name:
    <?php
        $name = $form->get('name');
        //echo $formLabel->openTag().$name->getOption('label');
        echo $this->formInput($name);
        //echo $this->formElementErrors($name);
        //echo $formLabel->closeTag();
    ?>
</div>

<div class="form_element">
    Email:
    <?php
    $email = $form->get('email');
    //echo $formLabel->openTag().$name->getOption('label');
    echo $this->formInput($email);
    //echo $this->formElementErrors($name);
    //echo $formLabel->closeTag();
    ?>
</div>

<?php echo $this->formElement($form->get('send')) ?>

<?php
// Render the opening tag
echo $this->form()->closeTag($form);

?>